### ISSUE TITLE
#US02 Como visitante quiero ingresar a una página principal que esté dividida en secciones para poder encontrar todo el contenido fácilmente.

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#72]
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/41
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/42
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/49
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/50
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/51
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/52
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/53
