### ISSUE TITLE
#US03 Como visitante quiero disponer de una pagina de inicio donde tenga un resumen de todo el contenido del portal para tener una mejor experiencia visual.

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#74]
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/15
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/19
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/18
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/16
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/17
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/87
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/88
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/89
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/90
